# fly.toml app configuration file generated for line-translation-bot on 2024-02-29T14:39:30+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'line-translation-bot'
primary_region = 'nrt'

[build]

[env]
  CHANNEL_ACCESS_TOKEN = 'vRj0MRLUcnfDF9qVmdvogwZlqTiK2nW05VeWiR8Qyb4lM7pkzVqHJaJyzYHQZPkW/w3ufgiav31hK2LZ4/GloyucKxiyFNM69Oxdl66viD471TFIhZMxFR6VGAGgdrVWfhic3oki5LchGwYJvs/mSQdB04t89/1O/w1cDnyilFU='
  CHANNEL_SECRET = 'b111f809e69fcd8961a60372f8e370ec'
  DEEPL_AUTH_TOKEN = '9f821740-6006-4526-a1f9-96450bb22b7f:fx'
  GOOGLE_API_KEY = 'AIzaSyCdjlDiThcK_MFuVCbw80VWwvTw9J0FU6o'
  GOOGLE_PROJ_ID = 'lunar-temple-409603'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
